name: NFCReaderTool
options:
  bundleIdPrefix: com.jetteck
  deploymentTarget:
    iOS: "15.0"
targets:
  NFCReaderTool:
    platform: iOS
    type: application
    sources: [ . ]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jetteck.nfcreadertool
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    info:
      path: Info.plist
